### PR TITLE
Added the Safari Push Notification Message.

### PR DESCRIPTION
**Pull request by delitestudio**
This is a custom Message implementing the Safari Push Notification message payload.

### CODE REVIEW

**Comment by delitestudio** [comment]
If needed we can add an example file as sample_push.php, sample_push_custom.php, etc.
Hope it helps.

**Comment by duccio** [comment]
Hello @delitestudio, sorry for the delay. If you an add an example file (e.g. sample_push_safari.php) I will merge ASAP. Thanks 😉

**Comment by delitestudio** [comment]
Hi @duccio, I have committed a sample_push_safari.php file that uses the same text used in the [official Apple documentation](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/PushNotifications/PushNotifications.html#//apple_ref/doc/uid/TP40013225-CH3-SW22) to ease users integrating Safari notifications in their PHP projects.

**Comment by duccio** [comment]
Thank you so much @delitestudio!

**Pull request merged**
